### ISSUE TITLE
Review Anforderungen

### ISSUE THREAD

**Issue by alexsuter** [wuethrich44/zusammenfassung-appe#14]

**Comment by fabwu** [comment]
@alexander-suter Review Pleeease!

**Comment by alexsuter** [comment]
@wuethrich44 
Super! Guet detailliert, findi guet, will mer da eh nid so viel Content hend!

Ich ha es paar Sache apasst. Luegsch mal die Änderige a. Vorallem hani no en Section ibaut "User Story vs Use Case". Da chasch villicht au no ergänze.
