### ISSUE TITLE
SOLID

### ISSUE THREAD

**Issue by alexsuter** [wuethrich44/zusammenfassung-appe#5]

**Comment by alexsuter** [comment]
@wuethrich44 wemmer bi de zämäfassig chapters mit "von gisler, von hofstetter usw. " usenäh? und als chapter eher "architektur, solid, modelieren" machen ?

**Comment by fabwu** [comment]
jo da chame mache aber ich du zerscht no das kapital mache und den chames ändere oke?

**Comment by alexsuter** [comment]
jo
