### ISSUE TITLE
Review Persistenz

### ISSUE THREAD

**Issue by alexsuter** [wuethrich44/zusammenfassung-appe#8]

**Comment by alexsuter** [comment]
@wuethrich44 review
@wuethrich44 review

**Comment by alexsuter** [comment]
p.s üsi repos sind glaub ich langsam bekannt ...

**Comment by fabwu** [comment]
das denki scho aber spdf gits erst nach dr mep :shipit:

**Comment by fabwu** [comment]
Hehe was wir im DMG gelernt haben ist nicht praxistauglich :smile:
